title: Corinne's Webpage
email:
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://econocorinne.github.io"

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle

timezone: America/New_York
